---
title: Galactic Society
timezone: UTC
email: admin@galacticsociety.org
site_admin: Charles
logo: "/uploads/logo.jpg"
motto: Cubilia enim adipiscing orci faucibus at Vestibulum
keywords: Galaxy, Culture, Community, Spacetime
description: >- # this means to ignore newlines until "baseurl:"
  Mauris neque quam, fermentum ut nisl vitae, convallis maximus nisl.
  Sed mattis nunc id lorem euismod placerat. Vivamus porttitor magna
  enim, ac accumsan tortor cursus at. Phasellus sed ultricies mi non
  congue ullam corper.

baseurl: "/" # the subpath of your site, e.g. /blog /galacticsociety.github.io
url: "https://galacticsociety.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

#Latent Semantic Indexing for similarity bewtween documents.
lsi: true

# Collection configurations
# These collections will enable to sort types of products and loop through that
# type to be displayed on a page. As an example, I have 10 "3D" items, all 10 items
# will be displayed when a category is selected on the product main index page.
collections_dir: collections

collections:
  posts:
    output: true
    permalink: /:year/:month/:day/:title/
  legal:
    output: true
    permalink: /legal/:path/

permalink: /:categories/:year/:month/:day/:title/ #Built in options include: date, pretty, ordinal, weekdate, none; learn more here: https://jekyllrb.com/docs/permalinks/

############################################################
# Old jekyll-paginate pagination logic
#   Uncomment thew two entries below to demonstrate how this new gem
#   retains backwards compatibility with the old pagination logic
#   AS OF JANUARY 2018 this code does not work anymore!
#paginate: 3
#paginate_path: "/legacy/page:num/"

# Build settings
plugins:
  - jekyll-feed #manually generated rss.xml https://jekyllrb.com/tutorials/convert-site-to-jekyll/#10-rss-feed
  - jekyll-menus
  - jekyll-archives
  - jekyll-paginate-v2
  - jekyll/tagging

sass:
  style: compressed
  sass_dir: _scss

############################################################
# Site configuration for the Jekyll 3 Pagination Gem
# The values here represent the defaults if nothing is set
pagination:

  # Site-wide kill switch, disabled here it doesn't run at all
  enabled: true

  # Set to 'true' to enable pagination debugging. This can be enabled in the site config or only for individual pagination pages
  debug: true

  # The default document collection to paginate if nothing is specified ('posts' is default)
  collection: 'posts'

  # How many objects per paginated page, used to be `paginate` (default: 0, means all)
  per_page: 5

  # The permalink structure for the paginated pages (this can be any level deep)
  permalink: '/:num/' # Pages are index.html inside this folder (default)
  #permalink: '/page/:num.html' # Pages are simple html files
  #permalink: '/page/:num' # Pages are html files, linked jekyll extensionless permalink style.

  # Optional the title format for the paginated pages (supports :title for original page title, :num for pagination page number, :max for total number of pages)
  title: ':title - page :num'

  # Limit how many pagenated pages to create (default: 0, means all)
  limit: 0

  # Optional, defines the field that the posts should be sorted on (omit to default to 'date')
  sort_field: 'date'

  # Optional, sorts the posts in reverse order (omit to default decending or sort_reverse: true)
  sort_reverse: true

  # Optional, the default category to use, omit or just leave this as 'posts' to get a backwards-compatible behavior (all posts)
  category: 'posts'

  # Optional, the default tag to use, omit to disable
  tag: ''

  # Optional, the default locale to use, omit to disable (depends on a field 'locale' to be specified in the posts,
  # in reality this can be any value, suggested are the Microsoft locale-codes (e.g. en_US, en_GB) or simply the ISO-639 language code )
  locale: ''

 # Optional,omit or set both before and after to zero to disable.
 # Controls how the pagination trail for the paginated pages look like.
  trail:
    before: 3
    after: 1

  # Optional, the default file extension for generated pages (e.g html, json, xml).
  # Internally this is set to html by default
  extension: html

  # Optional, the default name of the index file for generated pages (e.g. 'index.html')
  # Without file extension
  indexpage: 'index'

############################################################

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
  exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Reading extra files
# Every file or directory beginning with the following characters: ., _ , # or ~
# in the source directory will not be included in the destination folder. Such
# paths will have to be explicitly specified via the config file in the include
# directive to make sure they’re copied over:
#

  include:
#  - _pages
