---
title: Galactic Society
timezone: UTC
collections:
  legal:
    title: Legal
    output: true
    permalink: "/legal/:path/"
  paginator.posts:
    title: Posts
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: admin@galacticsociety.org
site_admin: Charles
logo: "/uploads/logo.jpg"
motto: Cubilia enim adipiscing orci faucibus at Vestibulum
keywords: Galaxy, Culture, Community, Spacetime
description: Mauris neque quam, fermentum ut nisl vitae, convallis maximus nisl. Sed
  mattis nunc id lorem euismod placerat. Vivamus porttitor magna enim, ac accumsan
  tortor cursus at. Phasellus sed ultricies mi non congue ullam corper.
baseurl: "/"
url: https://galacticsociety.github.io/
lsi: true
collections_dir: collections
permalink: "/:categories/:year/:month/:day/:title/"
plugins:
- jekyll-feed
- jekyll-menus
- jekyll-archives
- jekyll-paginate-v2
- jekyll/tagging
sass:
  style: compressed
  sass_dir: _scss
pagination:
  enabled: true
  debug: true
  collection: posts
  per_page: 5
  permalink: "/:num/"
  title: ":title - page :num"
  limit: 0
  sort_field: date
  sort_reverse: true
  category: posts
  tag: 
  locale: 
  trail:
    before: 3
    after: 1
  extension: html
  indexpage: index
  exclude: 
  include: 
