---
title: Galactic Society
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: example@galacticsociety.org
site_admin: Charles
logo: "/uploads/logo.jpg"
motto: Cubilia enim adipiscing orci faucibus at Vestibulum
keywords: Galaxy, Culture, Community, Spacetime
description: Mauris neque quam, fermentum ut nisl vitae, convallis maximus nisl. Sed
  mattis nunc id lorem euismod placerat. Vivamus porttitor magna enim, ac accumsan
  tortor cursus at. Phasellus sed ultricies mi non congue ullam corper.
baseurl: "/galacticsociety.github.io"
url: https://galacticsociety.github.io
github_username: example
permalink: "/:categories/:year/:month/:day/:title/"
paginate: 3
paginate_path: "/blog/:num/"
paypal_acct: example
cashapp_acct: example
dwolla_acct: example
patreon: example
bitcoin: example
ethereum: example
twitter_username: example
linkedin_username: example
instagram_username: example
facebook_username: example
plugins:
- jekyll-feed
- jekyll-menus
- jekyll-archives
- jekyll-paginate
sass:
  style: compressed
  sass_dir: _scss
  exclude: 
